### ISSUE TITLE
[bug] Error when trying to set an event of calendar all day if assigned to is set to a group

### ISSUE THREAD

**Issue by vslonska** [YetiForceCompany/YetiForce#11]
Hello,
If I want to set "all day" for an event and not an hour of beginning and ending, I have to assign myself, set to all day, and then reassign the event to a group.
I I assign the event to a group first I have an error and I can't create the event (error, contact your admin).
Thank you,

**Comment by vslonska** [comment]
Hello,
We are still unable to set an event for "all day" if the event is not assigned to the user who creates it, even after the last update.

**Comment by vslonska** [comment]
Hello,
I found the trace of the bug in system.log : 

```
====================================================================================================================================
2024-09-24 10:09:31.6465 [error][] - Failed to parse time string (2024-09-28 :00) at position 11 (:): Unexpected character
DateMalformedStringException: Failed to parse time string (2024-09-28 :00) at position 11 (:): Unexpected character in /html/app/Fields/DateTime.php:182
Stack trace:
#0 /html/app/Fields/DateTime.php(182): DateTime->__construct()
#1 /html/modules/Calendar/handlers/CalendarHandler.php(73): App\Fields\DateTime::getDiff()
#2 /html/app/EventHandler.php(544): Calendar_CalendarHandler_Handler->entityBeforeSave()
#3 /html/app/EventHandler.php(520): App\EventHandler->triggerHandler()
#4 /html/modules/Vtiger/models/Record.php(550): App\EventHandler->trigger()
#5 /html/modules/Vtiger/actions/Save.php(112): Vtiger_Record_Model->save()
#6 /html/modules/Calendar/actions/SaveAjax.php(17): Vtiger_Save_Action->saveRecord()
#7 /html/modules/Vtiger/actions/SaveAjax.php(25): Calendar_SaveAjax_Action->saveRecord()
#8 /html/include/main/WebUI.php(161): Vtiger_SaveAjax_Action->process()
#9 /html/index.php(26): Vtiger_WebUI->process()
#10 /html/public_html/index.php(13): require('...')
#11 {main}
 - 0 include/main/WebUI.php:164  >>  App\Log->error('Failed to parse time string (2024-09-28 :00) at position 11 (:): Unexpected character
DateMalformedStringException: Failed to parse time string (2024-09-28 :00) at position 11 (:): Unexpected character in app/Fields/DateTime.php:182
Stack trace:
#0 app/Fields/DateTime.php(182): DateTime->__construct()
#1 modules/Calendar/handlers/CalendarHandler.php(73): App\\Fields\\DateTime::getDiff()
#2 app/EventHandler.php(544): Calendar_CalendarHandler_Handler->entityBeforeSave()
#3 app/EventHandler.php(520): App\\EventHandler->triggerHandler()
#4 modules/Vtiger/models/Record.php(550): App\\EventHandler->trigger()
#5 modules/Vtiger/actions/Save.php(112): Vtiger_Record_Model->save()
#6 modules/Calendar/actions/SaveAjax.php(17): Vtiger_Save_Action->saveRecord()
#7 modules/Vtiger/actions/SaveAjax.php(25): Calendar_SaveAjax_Action->saveRecord()
#8 include/main/WebUI.php(161): Vtiger_SaveAjax_Action->process()
#9 index.php(26): Vtiger_WebUI->process()
#10 public_html/index.php(13): require(\'...\')
#11 {main}')
 - 1 index.php:26  >>  Vtiger_WebUI->process()
 - 2 public_html/index.php:13  >>  require('index.php')
2024-09-24 10:09:31.6073 [info][[application]] - 
$_POST = ['_csrf'=>'sid:45c34f5089408391f19adaf894085a9cd5473461,1727165353','module'=>'Calendar','action'=>'SaveAjax','fromView'=>'QuickCreate','mappingRelatedField'=>'[]','listFilterFields'=>'[]','defaultOtherEventDuration'=>'[{"activitytype":"Call","duration":"60"},{"activitytype":"Meeting","duration":"60"},{"activitytype":"Task","duration":"60"}]','userChangedEndDateTime'=>'0','subject'=>'Test Todoeldia','date_start'=>'28-09-2024','time_start'=>'00:00','due_date'=>'28-09-2024','time_end'=>'00:30','allday'=>'1','shownerid'=>['16'],'popupReferenceModule'=>'Contacts','link'=>'0','link_display'=>'','process'=>'0','linkextend'=>'0','linkextend_display'=>'','meeting_url'=>'','description'=>'','assignation'=>'','assigned_user_id'=>'16','activitystatus'=>'PLL_PLANNED','activitytype'=>'Meeting','state'=>'PLL_OPAQUE','reminder_time'=>'0','remdays'=>'0','remhrs'=>'0','remmin'=>'1','visibility'=>'Public','inviteesid'=>'[]']
$_COOKIE = DELETED
$_SESSION = DELETED
_HEADERS = DELETED
====================================================================================================================================
```

**Comment by rskrzypczak** [comment]
Fixed in YF7.0.3
Thanks!

**Comment by vslonska** [comment]
Thank you !
