### ISSUE TITLE
How to force mail scanner to stop after timeout

### ISSUE THREAD

**Issue by vslonska** [YetiForceCompany/YetiForce#25]
Hello,
I quite often have a problem with the mail scanner, which goes on and on and on... even if the Cron is ok and running well, and the server configured as recommended.
I have to manually stop it and to wait a few minutes for the cron to start it to get it work again.
![Capture d’écran du 2024-09-12 22-29-23](https://github.com/user-attachments/assets/3b008541-0f46-4abc-99b9-504260d9db9a)

I would like to automatically stop it if it doesn't end after some time.
Is it possible ?

Thank you,
Regards,

**Comment by garryatbrighton** [comment]
Go to your database and fire:
delete from vtiger_ossmails_logs where status = 1 limit 1;

I have set it in cron:
*/5 * * * * /usr/bin/mysql -u[user] -[password]< /var/www/html/mysql-commands/clearmailscanner.sql > /var/www/html/cache/logs/cronmysql.log 2>&1

clearmailscanner.sql:
USE mydatabase;
delete from vtiger_ossmails_logs where status = 1 limit 1;

**Comment by rskrzypczak** [comment]
@garryatbrighton This will not solve the problem in any way.

The problem in such cases is always the issue of parsing the email.
The YF system cannot handle it for some reason.
The problem is usually the attachments, headers or the email content itself.
So I recommend activating the application logs and see what exactly is the problem.

By the way, if you are using version 6.5 or lower, I recommend updating to 7.0.x, because the entire mechanism of the email scanner has been thoroughly rebuilt and it will most likely reduce the number of errors in this area.

**Comment by vslonska** [comment]
Thank you for your answers.
I use the last version of Yetiforce.
Which logs should I activate? 

I also activated the option in config/main.php to stop Cron after 1 hour if the task is not completed but it doesn't stop the email scanner.

Thank you,
Regards,

**Comment by rskrzypczak** [comment]
> Which logs should I activate?

`config/Debug.php`
```php
public static $LOG_TO_FILE = true;
public static $LOG_LEVELS = ['error','warning'];
public static $LOG_TRACE_LEVEL = 9;
```
Logs will be registered in the following file: `cache/logs/system.log`

**Comment by vslonska** [comment]
Hello,
I have in te log file :

```
2024-09-23 22:13:10.323 [error][] - Mail Scanner - Account: 1, folder: INBOX, UID: 581, message: ERR_ILLEGAL_FIELD_VALUE||subject||OSSMailView||




Échec de certaines corrections pour Indexation des pages problèmes
 du site domain.fr

 - 0 app/Mail/Scanner.php:152  >>  App\Log->error('Mail Scanner - Account: 1, folder: INBOX, UID: 581, message: ERR_ILLEGAL_FIELD_VALUE||subject||OSSMailView||




Échec de certaines corrections pour Indexation des pages problèmes
 du site domain.fr
')
 - 1 modules/OSSMailScanner/crons/Scann.php:46  >>  App\Mail\Scanner->run()
 - 2 cron.php:100  >>  OSSMailScanner_Scann_Cron->process()
2024-09-23 22:13:01.2318 [info][[application]] -
$_SESSION = ['last_activity'=>1727122381.261789]
_HEADERS = []

```
Do you have any idea ?
Thanks,

**Comment by rskrzypczak** [comment]
It seems that the subject of the email is the source of the problem here. It may contain HTML syntax or some other unacceptable characters. Also check if you have uft8mb4 or uft8mb3 database encoding. If you can, please provide the subject of the email.

**Comment by vslonska** [comment]
Hello,
Thanks for the answer.

It's a message from Google Search Console. In the headers I have : 
```
subject Échec de certaines corrections pour Indexation des pages problèmes du site mydomain.fr

fromGoogle Search Console Team <sc-noreply@google.com>
```
If I open the system.log file with a local text editor I see (with an encoding problem) : 
`Ãchec de certaines corrections pour Indexation des pages problÃ¨mes`

I don't see any encoding problem in the subject of the email in the inbox (Rouncube in Yetiforce or in the original mailbox of the provider).

The encoding of the database is correct I think : 
![Screenshot 2024-09-24 at 09-28-13 Configuration serveur](https://github.com/user-attachments/assets/9a283dd7-349d-4fb0-9f6c-501cc539eab6)

I can send you the problematic email if you want.

I also have another error :
```
2024-09-23 23:59:19.2802 [error][[App\Fields\File]] - Error during file validation: mj_logo_with_text_color.svg | Size: 4362
 App\Exceptions\DangerousFile: ERR_FILE_ILLEGAL_FORMAT in app/Fields/File.php:1279
Stack trace:
#0 app/Fields/File.php(444): App\Fields\File->validateFormat()
#1 app/Fields/File.php(474): App\Fields\File->validate()
#2 app/Mail/Message/Imap.php(558): App\Fields\File->validateAndSecure()
#3 app/Mail/Message/Imap.php(528): App\Mail\Message\Imap->getFileFromImage()
#4 app/Mail/Message/Imap.php(378): App\Mail\Message\Imap->parseBody()
#5 app/Mail/Message/Imap.php(430): App\Mail\Message\Imap->getBody()
#6 app/Mail/ScannerAction/CreatedMail.php(68): App\Mail\Message\Imap->hasAttachments()
#7 modules/OSSMail/views/MailActionBar.php(50): App\Mail\ScannerAction\CreatedMail->process()
#8 include/main/WebUI.php(161): OSSMail_MailActionBar_View->process()
#9 index.php(26): Vtiger_WebUI->process()
#10 public_html/index.php(13): require('...')
#11 {main}
```

**Comment by davide-alghi** [comment]
Hi all,
I have the same problem with YF7.0.3

`[error][] - Mail Scanner - Account: 1, folder: INBOX, UID: 10577, message: ERR_ILLEGAL_FIELD_VALUE||subject||OSSMailView||Comprobante fiscal electr�nico de la cuenta`

I think the reason is the char in "Comprobante fiscal electrónico de la cuenta"

the big problem is that every time the scanner restart, it tries to import the same email and it crashes.

any suggestion/workaround to bypass this problem?

**Comment by rskrzypczak** [comment]
you can increase the uid of the last scan in the `u_yf_mailscanner_folders` table.

Can you send us a raw header of your message? Only there is the real content of the subject and the encoding in which it was written indicated. of course you can cover up part of the data.
https://mxtoolbox.com/public/content/emailheaders/

**Comment by davide-alghi** [comment]
there are a lot of emails with that problems. I do some checks first, then I load/send the raw header

**Comment by davide-alghi** [comment]
Hi @rskrzypczak,
the problem occurs when sender sends an email in charset iso-8859-1.

I exported the email (.eml) from RoundCube and deleted the sensitive data (and the attachment).
where can I send you the eml file?

**Comment by rskrzypczak** [comment]
> _the problem occurs when sender sends an email in charset iso-8859-1._

 Thanks.

> _where can I send you the eml file?_

wherever you want, it can be on `hello`

**Comment by davide-alghi** [comment]
just sent in `hello`

**Comment by davide-alghi** [comment]
Hi @rskrzypczak ,

any news about this problem?

**Comment by rskrzypczak** [comment]
Yes, in short..
I looked into it in more detail and came to the conclusion that

> There are a lot of broken mail user agents that don't follow the specification and don't produce correct MIME headers.

The sample email you sent, thanks for that by the way, confirmed my belief.

I looked through other leading header tools and each one works the same. Interestingly, some older versions of these tools worked "better" because they decoded latin1 by default ;), which is an obvious mistake. Programs like Thunderbird, Roundcube or any others have their own methods for identifying encoding and dealing with "incorrect" encoding of the email subject, but they work more or less the same, they just have more exceptions. Anyway, I added a small improvement in the area of ​​parsing emails in general, which should eliminate the bugs described in this issue.
We will publish another version soon, which will include this and other fixes. So if any errors appear in the future, please send specific examples, i.e. .eml files or at least just headers (https://mxtoolbox.com/public/content/emailheaders/)

PS a quick hack that will probably solve some of the problems is to change the decoding function in `\vendor\webklex\php-imap\src\config\imap.php` from `utf-8` to `iconv`
```
'decoding' => [
        'options' => [
            'header' => 'utf-8',
```

**Comment by davide-alghi** [comment]
@rskrzypczak wow ... tnx a lot

**Comment by rskrzypczak** [comment]
YF 7.0.4 contains many fixes in the area of ​​encoding and the general operation of the mail scanner. This should eliminate most if not all of the issues reported here.
