### ISSUE TITLE
[YF7.0.2] Record no longer editable

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForce#73]
**Conditions**

1. Inventory module (extended)
2. lineitem includes a TEXT custom field
3. module record contains a deleted product/service

NB: screenshots from https://demo.yetiforce.com, `system.log` from my local instance

![Schermata del 2024-12-30 10-16-51](https://github.com/user-attachments/assets/5f1db0c8-c489-4e33-8667-38bb2308b92c)
![Schermata del 2024-12-30 10-17-27](https://github.com/user-attachments/assets/42cd063d-eb2d-4fbd-b4ad-370a1c011082)
![Schermata del 2024-12-30 10-17-36](https://github.com/user-attachments/assets/0c6d74b9-a03b-4e61-8fa5-f34d214e71fb)

`system.log`

`2024-12-30 10:05:31.9806 [error][] - Vtiger_Basic_InventoryField::getMapDetail(): Argument #1 ($related) must be of type string, null given, called in /var/www/html/development/yf_7.0/AA/cache/templates_c/basic/80ac4432df04fb9c0aedad5a673242276597f450_0.file.EditViewValue.tpl.php on line 26
TypeError: Vtiger_Basic_InventoryField::getMapDetail(): Argument #1 ($related) must be of type string, null given, called in /var/www/html/development/yf_7.0/AA/cache/templates_c/basic/80ac4432df04fb9c0aedad5a673242276597f450_0.file.EditViewValue.tpl.php on line 26 and defined in /var/www/html/development/yf_7.0/AA/modules/Vtiger/inventoryfields/Basic.php:667
Stack trace:
#0 /var/www/html/development/yf_7.0/AA/cache/templates_c/basic/80ac4432df04fb9c0aedad5a673242276597f450_0.file.EditViewValue.tpl.php(26): Vtiger_Basic_InventoryField->getMapDetail()
#1 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6751a774beebe6_63345068()
#2 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#3 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(384): Smarty_Template_Compiled->render()
#4 /var/www/html/development/yf_7.0/AA/cache/templates_c/basic/2bcf94606508552c690683f71ef575001e96273a_0.file.InventoryItem.tpl.php(69): Smarty_Internal_Template->_subTemplateRender()
#5 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6751a774bc2f23_41478309()
#6 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#7 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(384): Smarty_Template_Compiled->render()
#8 /var/www/html/development/yf_7.0/AA/cache/templates_c/basic/a2faf9b2df866785fe3aac29ab5127f0a83fb0a4_0.file.InventoryBlock.tpl.php(71): Smarty_Internal_Template->_subTemplateRender()
#9 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6751a774ba8297_59870386()
#10 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#11 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render()
#12 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render()
#13 /var/www/html/development/yf_7.0/AA/cache/templates_c/basic/9a7d7d3ea208a2f285921119c0c0f626bc485b89_0.file.Inventory.tpl.php(57): Smarty_Internal_Template->_subTemplateRender()
#14 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6751a774b35565_50523655()
#15 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#16 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render()
#17 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render()
#18 /var/www/html/development/yf_7.0/AA/cache/templates_c/basic/0547d23b20e62c4020ebec619e285d97d3fafec6_0.file.EditViewBlocks.tpl.php(82): Smarty_Internal_Template->_subTemplateRender()
#19 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6751a774a1ee86_36452604()
#20 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#21 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render()
#22 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(386): Smarty_Internal_Template->render()
#23 /var/www/html/development/yf_7.0/AA/cache/templates_c/basic/45fc9e5313a0a212c0a3eb0a4d2338d5d9fa3ffd_0.file.EditView.tpl.php(24): Smarty_Internal_Template->_subTemplateRender()
#24 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6751a7749f37b2_51682525()
#25 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#26 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(217): Smarty_Template_Compiled->render()
#27 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render()
#28 /var/www/html/development/yf_7.0/AA/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute()
#29 /var/www/html/development/yf_7.0/AA/include/runtime/Viewer.php(213): Smarty_Internal_TemplateBase->display()
#30 /var/www/html/development/yf_7.0/AA/modules/Vtiger/views/Edit.php(146): Vtiger_Viewer->view()
#31 /var/www/html/development/yf_7.0/AA/include/main/WebUI.php(161): Vtiger_Edit_View->process()
#32 /var/www/html/development/yf_7.0/AA/index.php(26): Vtiger_WebUI->process()
#33 /var/www/html/development/yf_7.0/AA/public_html/index.php(13): require('...')
#34 {main}
2024-12-30 10:05:31.8423 [info][[application]] - 
$_GET = ['module'=>'MyTestModule','view'=>'Edit','mid'=>'169','record'=>'143']
$_COOKIE = ['YTSID'=>'1k63u8p25ir07g1frbntrjl09s']
$_SESSION = ['CSP_TOKEN'=>'9d838e87ee6d3f2918d53c0fdffa128215af0bc75a9d4bdd367089f5aff97118','last_activity'=>1735549531.842894,'fingerprint'=>'2750bc42-702e-4cbe-bae5-798f171389e1','user_agent'=>'Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0','UserAuthMethod'=>'PASSWORD','app_unique_key'=>'6WYPfPTQI71P9yqNJ49iNoam8avFMUan381WfXyA','user_name'=>'davide','full_user_name'=>'Alghi Davide','authenticated_user_id'=>1,'DashBoard'=>['Home'=>['LastDashBoardId'=>1]],'lvs'=>['MyTestModule'=>['viewname'=>134]]]
_HEADERS = ['Host'=>'www.yeticrm70.com','Te'=>'trailers','Priority'=>'u=0, i','Sec-Fetch-User'=>'?1','Sec-Fetch-Site'=>'same-origin','Sec-Fetch-Mode'=>'navigate','Sec-Fetch-Dest'=>'document','Upgrade-Insecure-Requests'=>'1','Cookie'=>'YTSID=1k63u8p25ir07g1frbntrjl09s','Accept-Encoding'=>'gzip, deflate, br, zstd','Accept-Language'=>'it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3','Accept'=>'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8','User-Agent'=>'Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0','Authorization'=>'']
$stability = ['error_reporting'=>'E_ALL & ~E_NOTICE','output_buffering'=>'1']
$security = ['disable_functions'=>'']
$libraries = ['pdo_sqlsrv'=>'LBL_NO','mongodb'=>'LBL_NO']
$performance = ['opcache.save_comments'=>'1']
$environment = ['currentUser'=>' (uid:33)']
$functionalVerification = ['branding'=>'No']`

**Comment by rskrzypczak** [comment]
Fixed in YF7.0.3

in 7.0.3 errors should no longer occur in the case you mentioned. 
Additionally, added verification if the Product/Service exists somewhere in the advanced block before deleting ;)

![Image](https://github.com/user-attachments/assets/c09386fb-b576-4391-b930-e9d1d88881d2)

Thanks!

**Comment by davide-alghi** [comment]
great ... yes I saw the message to translate, on Crowdin
